services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inventory-network

  backend:
    build:
      context: ./ws
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ws:/app
    env_file:
      - ./.env
    depends_on:
      mysql:
        condition: service_healthy
    command: python ws.py
    restart: always
    networks:
      - inventory-network

  frontend:
    build:
      context: ./ui
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - backend
    restart: always
    networks:
      - inventory-network

volumes:
  mysql_data:

networks:
  inventory-network:
    driver: bridge