"""Add accessible_platforms to User model

Revision ID: d074641e182a
Revises: 81ebad1996d3
Create Date: 2025-10-10 07:41:53.306277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd074641e182a'
down_revision = '81ebad1996d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accessible_platforms', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('accessible_platforms')

    # ### end Alembic commands ###
