"""Add platform column to models

Revision ID: 81ebad1996d3
Revises: 79b954a0cd6a
Create Date: 2025-10-10 06:43:34.333838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81ebad1996d3'
down_revision = '79b954a0cd6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=False))

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=False))

    with op.batch_alter_table('business_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=False))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=False))
        batch_op.alter_column('project_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('project_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('platform')

    with op.batch_alter_table('business_rules', schema=None) as batch_op:
        batch_op.drop_column('platform')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('platform')

    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
